In [1]:
import numpy as np

## Introduction to NumPy
•	NumPy (Numerical Python) is a library for the Python programming language that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

### What is an Array in Python?

* An array is a collection of items stored at contiguous memory locations. 
* The idea is to store multiple items of the same type together.

### Why Use NumPy?
•	In Python we have lists that serve the purpose of arrays, but they are slow to process.

•	NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

•	The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

•	Arrays are very frequently used in data science, where speed and resources are very important.
ilable.

### Why is NumPy Faster Than Lists?

•	NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

•	This behaviour is called locality of reference in computer science.

•	This is the main reason why NumPy is faster than lists. Also, it is optimized to work with latest CPU architectures.

•	No need for data type checking.

•	Item wise computations available.

## Create numpy ndarray object

#### 0 dimensional array

* A 0-dimensional array (also known as a scalar) in NumPy is an array with no dimensions.
* It simply holds a single value.

In [2]:
arr=np.array(34)
arr

array(34)

#### One dimensional array
* A 1-dimensional array in NumPy is essentially a simple list of values (also called a vector).
* It has only one axis, which is typically referred to as the length of the array.


In [3]:
oned=np.array([1,2,3,4])
oned

array([1, 2, 3, 4])

#### Two dimensional array

* An array that has 1-D arrays as its elements is called a 2-D array

In [4]:
twod=np.array([[1,2,3],[4,5,6]])
twod

array([[1, 2, 3],
       [4, 5, 6]])

#### 4*4 matrix

In [5]:
frfr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
frfr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 3*4 matrix

In [6]:
thfr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
thfr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
print(type(thfr))

<class 'numpy.ndarray'>


#### 3 dimensional array

* An array that has 2-D arrays(matrices) as its elements is called a 3-D array

In [8]:
threed=np.array([[[1, 2, 3],[4, 5, 6]], [[7, 8, 9],[10, 11, 12]]])
threed

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
three=np.array([
    [[1, 2, 3],[4, 5, 6],[1,2,3]],
    [[7, 8, 9],[10, 11, 12],[4,6,5]]
])
three

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 1,  2,  3]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 4,  6,  5]]])

# Properties of ndarray
•	ndim: Number of dimensions (axes) of the array.

•	shape: A tuple of integers indicating the size of the array in each dimension.

•	size: Total number of elements in the array.

•	dtype: Data type of the array elements


# Check Number of Dimensions?

•	NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.


In [10]:
#### To check dimensions
three.ndim

3

In [11]:
three.shape

(2, 3, 3)

In [12]:
three.size

18

In [13]:
print(type(three))

<class 'numpy.ndarray'>


In [14]:
three1=np.array([
    [[1,3,4,5,7],[4,3,2,0,7],[67,80,100,5,8]],
    [[4,8,5,8,9],[34,56,78,56,98],[23,56,32,12,11]]
])
three1

array([[[  1,   3,   4,   5,   7],
        [  4,   3,   2,   0,   7],
        [ 67,  80, 100,   5,   8]],

       [[  4,   8,   5,   8,   9],
        [ 34,  56,  78,  56,  98],
        [ 23,  56,  32,  12,  11]]])

In [15]:
three1.size

30

In [16]:
three1.shape

(2, 3, 5)

In [17]:
three1.ndim

3

In [18]:
three2=np.array([
    [[1,3,4,5,7],[4,3,2,0,7]],
    [[4,8,5,8,9],[34,56,78,56,98]],
    [[1,3,4,5,7],[4,3,2,0,7]]
])
three2

array([[[ 1,  3,  4,  5,  7],
        [ 4,  3,  2,  0,  7]],

       [[ 4,  8,  5,  8,  9],
        [34, 56, 78, 56, 98]],

       [[ 1,  3,  4,  5,  7],
        [ 4,  3,  2,  0,  7]]])

In [19]:
three2.size

30

In [20]:
three2.ndim

3

In [21]:
three2.shape

(3, 2, 5)

In [22]:
three2.dtype

dtype('int32')

## Accessing an element

In [23]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [24]:
arr[0]

1

In [25]:
arr[3]

4

In [26]:
arr2=np.array([
    [1,2,3,4],
    [5,6,7,8]    
])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
arr2[0,0]

1

In [28]:
arr2[0,1]

2

In [29]:
arr2[0,2]

3

In [30]:
arr3=np.array([
    [[1,2,3,4],[5,6,7,8]]  ,
    [[11,21,31,41],[51,61,71,81]] 
])
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[11, 21, 31, 41],
        [51, 61, 71, 81]]])

In [31]:
# Accessing element 7
arr3[0,1,2]

7

In [32]:
#Accessing element 81
arr3[1,1,3]

81

In [33]:
threedim=np.array([
      [[1,2,3],[4,5,6]],

      [[4,5,6],[7,6,8]]
])

In [34]:
threedim

array([[[1, 2, 3],
        [4, 5, 6]],

       [[4, 5, 6],
        [7, 6, 8]]])

### WORK 

### Zero dimension

In [35]:
zero=np.array(25)
zero

array(25)

In [36]:
print(type(zero))

<class 'numpy.ndarray'>


In [37]:
zero.ndim

0

In [38]:
zero.size

1

### One dimension

In [39]:
one=np.array([1,2,3,4,5,6,7,8])
one


array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
one.ndim

1

In [41]:
one.size

8

In [42]:
one.shape

(8,)

### Two dimension

In [43]:
two=np.array([[1,2,3],[4,3,2]])
two

array([[1, 2, 3],
       [4, 3, 2]])

In [44]:
two.shape

(2, 3)

In [45]:
two.size

6

In [46]:
two.ndim

2

### Three dimension

In [47]:
three=np.array([
    [[1,2,3,4,5,6,7],[9,8,7,6,5,4,3]],
    [[1,23,34,45,56,2,7],[89,43,67,21,26,22,18]]
])

In [48]:
three

array([[[ 1,  2,  3,  4,  5,  6,  7],
        [ 9,  8,  7,  6,  5,  4,  3]],

       [[ 1, 23, 34, 45, 56,  2,  7],
        [89, 43, 67, 21, 26, 22, 18]]])

In [49]:
three.size

28

In [50]:
three.ndim

3

In [51]:
three.shape

(2, 2, 7)

In [52]:
# Accessing the element 45
three[1,0,3]

45

In [53]:
# Accessing element 8
three[0,1,1]

8

In [54]:
#Accessing elements from 8 to 4
three[0,1,1:5]

array([8, 7, 6, 5])

In [55]:
four_two_three=np.array([
    [[1,2,3],[2,3,3]],
    [[1,5,3],[2,3,3]],
    [[3,2,7],[0,3,5]],
    [[4,2,3],[8,3,6]]
])
four_two_three

array([[[1, 2, 3],
        [2, 3, 3]],

       [[1, 5, 3],
        [2, 3, 3]],

       [[3, 2, 7],
        [0, 3, 5]],

       [[4, 2, 3],
        [8, 3, 6]]])

In [56]:
four_two_three.shape

(4, 2, 3)

In [57]:
four_two_three.ndim

3

In [58]:
four_two_three.size

24

In [59]:
#Accessing element 7
four_two_three[2,1,2]

5

In [60]:
# Accessing element 0
four_two_three[2,1,0]

0

In [61]:
arra=np.array([
    [[1,2,3,4],[3,4,5,6]],
    
    [[11,12,13,14],[15,16,17,18]]
])

In [62]:
arra.shape

(2, 2, 4)

In [63]:
arra.size

16

In [64]:
arra.ndim

3

In [65]:
#Accessing element 5
arra[0,1,2]

5

# Negative slicing

In [66]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [67]:
arr1[-1]

4

In [68]:
arr2=np.array([[1,2,3,4,5],
               [1,2,3,6,7]
              ])
arr2

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 6, 7]])

In [69]:
arr2[-1,-2]

6

In [70]:
arr2[-2,-1]

5

In [71]:
arr3=np.array([
    [[1,2,3,4],[1,2,3,4]],
    [[1,2,3,4],[1,2,3,4]]
])
arr3

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [72]:
arr3.ndim

3

In [73]:
arr3.shape

(2, 2, 4)

In [74]:
arr3.size

16

In [75]:
#Accessing element 2
arr3[0,0,-3]

2

In [76]:
two_three=np.array([
    [1,2,3,4],[4,5,6,7]
    ])

In [77]:
two_three.shape

(2, 4)

In [78]:
two_three.ndim

2

In [79]:
two_three.size

8

In [80]:
# Accessing element 7
two_three[1,-1]

7

In [81]:
# Accessing element 6
two_three[1,-2]

6

In [82]:
two_three[-1,-2]

6

# Slicing arrays

In [83]:
two_three=np.array([
    [1,2,3,4],[4,5,6,7]
    ])
two_three

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [84]:
#Print 2,3,4
two_three[0,1:]

array([2, 3, 4])

In [85]:
three_six=np.array([
    [1,2,3,4,5,6],[6,7,8,9,0,1],
    [1,2,4,5,3,7]
])

In [86]:
three_six

array([[1, 2, 3, 4, 5, 6],
       [6, 7, 8, 9, 0, 1],
       [1, 2, 4, 5, 3, 7]])

In [87]:
three_six.shape

(3, 6)

In [88]:
three_six.size

18

In [89]:
three_six.ndim

2

In [90]:
three_six[:,2:5]

array([[3, 4, 5],
       [8, 9, 0],
       [4, 5, 3]])

In [91]:
three_six[-1,-5:-1]

array([2, 4, 5, 3])

In [92]:
arr3=np.array([
    [[1,2,3,4,5,6],[11,41,51,61,71,81],[12,22,32,42,52,62],[13,43,53,63,73,8]],
    [[15,25,35,45,55,65],[15,45,55,65,75,85],[16,26,36,46,56,66],[17,47,57,67,77,87]],
   
])
arr3

array([[[ 1,  2,  3,  4,  5,  6],
        [11, 41, 51, 61, 71, 81],
        [12, 22, 32, 42, 52, 62],
        [13, 43, 53, 63, 73,  8]],

       [[15, 25, 35, 45, 55, 65],
        [15, 45, 55, 65, 75, 85],
        [16, 26, 36, 46, 56, 66],
        [17, 47, 57, 67, 77, 87]]])

In [93]:
arr3.shape

(2, 4, 6)

In [94]:
arr3[0,:,:3]

array([[ 1,  2,  3],
       [11, 41, 51],
       [12, 22, 32],
       [13, 43, 53]])

In [95]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
arr[::2]

array([1, 3, 5, 7, 9])

In [97]:
arr[::3]

array([1, 4, 7])

In [98]:
arr2=np.array([[1,2,3,4,5,6,7],[4,5,6,7,4,8,9]])
arr2

array([[1, 2, 3, 4, 5, 6, 7],
       [4, 5, 6, 7, 4, 8, 9]])

In [99]:
arr2[:,:6:2]

array([[1, 3, 5],
       [4, 6, 4]])

In [100]:
thsix=np.array([[1,2,3,4,5,6],
          [7,8,9,10,11,12],
          [13,14,15,16,17,18]])
thsix

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [101]:
thsix[:,2::3]

array([[ 3,  6],
       [ 9, 12],
       [15, 18]])

In [102]:
thsix[:,::3]

array([[ 1,  4],
       [ 7, 10],
       [13, 16]])

In [103]:
fs=np.array([[1,2,3,4,5,6],[6,7,8,9,0,1],
    [1,2,4,5,3,7],[6,7,8,9,0,1]])
fs

array([[1, 2, 3, 4, 5, 6],
       [6, 7, 8, 9, 0, 1],
       [1, 2, 4, 5, 3, 7],
       [6, 7, 8, 9, 0, 1]])

In [104]:
fs.shape

(4, 6)

In [105]:
fs[1:,::3]

array([[6, 9],
       [1, 5],
       [6, 9]])

# Data Types in Python

By default Python have these data types:

•	strings - used to represent text data, the text is given under quote marks. Eg: "ABCD"

•	integer - used to represent integer numbers. Eg: -1, -2, -3

•	float - used to represent real numbers. Eg: 1.2, 42.42

•	boolean - used to represent True or False.

•	complex - used to represent complex numbers. Eg: 1.0 + 2.0j, 1.5 + 2.5j

# Data Types in NumPy

## NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.
## Below is a list of all data types in NumPy and the characters used to represent them.

•	i - integer

•	b - boolean

•	u - unsigned integer (i.e., zero and positive integers).astype(np.uint32)

•	f - float

•	c - complex float(Real+ imaginary part)

•	m - timedelta 
( The timedelta class in Python is part of the datetime module and represents the difference between two dates, times, or datetime objects. It is useful for performing arithmetic with date and time objects, such as adding or subtracting time intervals.)

•	M - datetime

•	O - object- (object data type is a general-purpose type that can hold any kind of data. It is often used in libraries like NumPy to handle heterogeneous data, such as arrays containing elements of different types or ragged arrays where sub-arrays have different lengths.)

•	S - string

•	U - unicode string

* ### 	In Python 3.x and modern programming environments, strings are Unicode by default. This means that when you define a string in Python, it can contain characters from any language or symbol set supported by Unicode.

* ### Strings in these contexts can only represent characters from a limited set, often limited to the ASCII character set (128 characters).

* ### Unicode strings, on the other hand, are designed to handle text from all writing systems around the world.


## Creating Arrays With a Defined Data Type
•	We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements


In [106]:
int=np.array([1,2,3,4])
int

array([1, 2, 3, 4])

In [107]:
print(int.dtype)

int32


In [108]:
int=np.array([1,2,3,4],dtype="S")
int

array([b'1', b'2', b'3', b'4'], dtype='|S1')

# Converting Data Type on Existing Arrays
•	The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

•	The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

•	The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

•	Eg:   arr=np.array([1.1, 2.1, 3.1])

     newarr=arr.astype('i')
     
     print(newarr)
     
     print(newarr.dtype)


In [109]:
int=np.array([1,2,3,4],dtype="f")
int

array([1., 2., 3., 4.], dtype=float32)

In [110]:
arr=np.array([1.1,2.1,3.1,4.1])
newarr=arr.astype("i")
print(newarr)
print(newarr.dtype)

[1 2 3 4]
int32


In [111]:
int=np.array([1,2,3,4],dtype="f")
float=int.astype("f")
print(float)
float.dtype

[1. 2. 3. 4.]


dtype('float32')

# The Difference Between Copy and View

•	The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
•	The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
•	The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.


## Copy

In [112]:
arr=np.array([1,2,3,4,5])
x=arr.copy()

In [113]:
print(arr)
print(x)

[1 2 3 4 5]
[1 2 3 4 5]


In [114]:
arr[0]=42
arr

array([42,  2,  3,  4,  5])

In [115]:
print(x)

[1 2 3 4 5]


In [116]:
arr1=np.array([11,12,13,14,15])
arr1

array([11, 12, 13, 14, 15])

In [117]:
arr1[1]=32

In [118]:
y=arr1.copy()

In [119]:
print(arr1)
print(y)

[11 32 13 14 15]
[11 32 13 14 15]


## View

In [120]:
arr=np.array([1,2,3,4,5])
x=arr.view()
print(arr)
print(x)

[1 2 3 4 5]
[1 2 3 4 5]


In [121]:
arr[0]=42

In [122]:
print(arr)

[42  2  3  4  5]


In [123]:
print(x)

[42  2  3  4  5]


In [124]:
x[2]=32

In [125]:
print(x)

[42  2 32  4  5]


In [126]:
print(arr)

[42  2 32  4  5]


# Check if Array Owns its Data
•	As mentioned above, copies own the data, and views does not own the data, but how can we check this?

•	Every NumPy array has the attribute base that returns None if the array owns the data.

•	Otherwise, the base  attribute refers to the original object.



## base()

In [127]:
arr=np.array([1,2,3,4,5,6,7])

In [128]:
x=arr.copy()

In [129]:
y=arr.view()

In [130]:
# if "none",that means copy of original
print(x.base)

None


In [131]:
# if "dataframe",that means view of original
print(y.base)

[1 2 3 4 5 6 7]


•	The copy returns None.

•	The view returns the original array.


# Shape of an Array
•	The shape of an array is the number of elements in each dimension.

•	NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.


In [132]:
threetwo=np.array([[1,2],[3,4],[5,6]])
threetwo

array([[1, 2],
       [3, 4],
       [5, 6]])

In [133]:
threetwo.shape

(3, 2)

In [134]:
print(threetwo.shape)

(3, 2)


In [135]:
frfr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [136]:
frfr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [137]:
print(frfr.shape)

(4, 4)


In [138]:
frfr.ndim

2

In [139]:
## reshaping arrays
frfr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]],ndmin=4)

In [140]:
frfr

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]]])

In [141]:
frfr.shape

(1, 1, 4, 4)

# Reshaping arrays

In [142]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [143]:
newarr=arr.reshape(4,3)

In [144]:
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [145]:
new1=arr.reshape(2,3,2)
new1

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [146]:
new1.base

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [147]:
# 2,3,5
ttf=np.array([[
    [1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],
    [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]
]])

In [148]:
ttf.shape

(2, 3, 5)

In [149]:
reshape=ttf.reshape(3,10)
reshape

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [150]:
reshape1=ttf.reshape(3,1,2,5)
reshape1

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]],


       [[[11, 12, 13, 14, 15],
         [ 1,  2,  3,  4,  5]]],


       [[[ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15]]]])

In [151]:
one=np.array([1,2,3,4],ndmin=6)

In [152]:
one

array([[[[[[1, 2, 3, 4]]]]]])

# Other functions that commonly used for array creation

## Arange()
* numpy.arange: Create an array with a range of values.

In [153]:
one=np.arange(0,10,2)
one

array([0, 2, 4, 6, 8])

In [154]:
one=np.arange(10,30)
one

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [155]:
re=one.reshape(2,10)

In [156]:
re

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

## ones()

In [157]:
one=np.ones(6,dtype="int")
one

array([1, 1, 1, 1, 1, 1])

In [158]:
arr=np.ones((3,4),dtype='int')

In [159]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [160]:
arr=np.ones((2,2,3),dtype="f")

In [161]:
arr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)

In [162]:
arr=np.ones((2,2,3),dtype="S")

In [163]:
arr

array([[[b'1', b'1', b'1'],
        [b'1', b'1', b'1']],

       [[b'1', b'1', b'1'],
        [b'1', b'1', b'1']]], dtype='|S1')

In [164]:
arr=np.ones((2,4,2),dtype="b")

In [165]:
arr

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]], dtype=int8)

## Zeros()

In [166]:
z=np.zeros(6,dtype="int")
z

array([0, 0, 0, 0, 0, 0])

In [167]:
zero=np.zeros((3,4),dtype="int")
zero

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [168]:
zero=np.zeros((3,2,8),dtype="f")
zero

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]], dtype=float32)

## Linspace()

In [169]:
arr=np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [170]:
arr1=np.linspace(0,50,5)
arr1

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [171]:
arr2=np.linspace(0,50,2)
arr2

array([ 0., 50.])

## diag()

In [172]:
f=np.diag([3,4,5,6,7,8])

In [173]:
f

array([[3, 0, 0, 0, 0, 0],
       [0, 4, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0],
       [0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 8]])

## eye()

In [174]:
three=np.eye(3,dtype="int")

In [175]:
three

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# mathematical operations

In [176]:
arrange=np.arange(20,35)
arrange

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [177]:
re=arrange.reshape(3,5)

In [178]:
re

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [179]:
a=np.arange(0,15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# •	numpy.add: Add two arrays element-wise

In [180]:
add=np.add(arrange,a)

In [181]:
add

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

# •	numpy.subtract: Subtract one array from another element-wise.

In [182]:
subtract=np.subtract(arrange,a)

In [183]:
subtract

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

# •	numpy.multiply: Multiply two arrays element-wise.

In [184]:
multiply=np.multiply(arrange,a)

In [185]:
multiply

array([  0,  21,  44,  69,  96, 125, 156, 189, 224, 261, 300, 341, 384,
       429, 476])

# •	numpy.dot: Dot product of two arrays.

In [186]:
dot=np.dot(arrange,a)

In [187]:
dot

3115

# •	numpy.sum: Sum of array elements.

In [188]:
sum=np.sum(arrange)
sum

405

# •	numpy.mean: Mean of array elements.

In [189]:
mean=np.mean(arrange)
mean

27.0

# •	Variance (np.var): Calculates the variance of the elements in the array.

In [190]:
var=np.var(arrange)
var

18.666666666666668

# •	numpy.std: Standard deviation of array elements.

In [191]:
std=np.std(arrange)
std

4.320493798938574

# •	numpy.max: Maximum value in an array.

In [192]:
max=np.max(arrange)
max

34

# •	numpy.max: Maximum value in an array.

In [193]:
min=np.min(arrange)
min

20

In [194]:
lin=np.linspace(0,20,8)
lin

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [195]:
re=lin.reshape(2,4)
re

array([[ 0.        ,  2.85714286,  5.71428571,  8.57142857],
       [11.42857143, 14.28571429, 17.14285714, 20.        ]])

In [196]:
flatten=re.reshape(-1)
flatten

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [197]:
maxlin=np.max(lin)
minlin=np.min(lin)
stdlin=np.std(lin)
varlin=np.var(lin)
meanlin=np.mean(lin)
sumlin=np.sum(lin)



In [198]:
maxlin

20.0

In [199]:
minlin

0.0

In [200]:
stdlin

6.546536707079771

In [201]:
varlin

42.85714285714286

In [202]:
sumlin

80.0

In [203]:
meanlin

10.0

In [204]:
one18=np.arange(1,19)

In [205]:
one18

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [206]:
three=one18.reshape(3,2,3)

In [207]:
three

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [208]:
one=three.reshape(-1)

In [209]:
one

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [210]:
max=np.max(one)
min=np.min(one)
std=np.std(one)
var=np.var(one)
mean=np.mean(one)
sum=np.sum(one)

In [211]:
max

18

In [212]:
min

1

In [213]:
std

5.188127472091127

In [214]:
var

26.916666666666668

In [215]:
mean

9.5

In [216]:
sum

171

### Iterating means going through elements one by one.
  
### As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
  
### If we iterate on a 1-D array it will go through each element one by one.

In [217]:
for i in one:
    print(i ,end=",")

1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,

In [218]:
two=np.arange(0,10)
two

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [219]:
twod=two.reshape(2,5)
twod

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [220]:
for i in twod:
    print(i)

[0 1 2 3 4]
[5 6 7 8 9]


In [221]:
for i in twod:
    for x in i:
         print(x)

0
1
2
3
4
5
6
7
8
9


In [222]:
threed=two.reshape(2,1,5)
threed

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [223]:
for i in threed:
    for x in i:
        for y in x:
            print(y,end=" ")

0 1 2 3 4 5 6 7 8 9 

# ITERATING ARRAYS USING nditer()

## •	The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration

In [224]:
arr=np.array([[[1,2],[3,4],[5,6],[7,8]]])

In [225]:
arr


array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [226]:
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8


In [227]:
for i in np.nditer(one):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


# Enumerated Iteration Using ndenumerate()

* ## 	Enumeration means mentioning sequence number of somethings one by one
* ## Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those use cases.s.


## Enumerate on following 1D array's elements

In [228]:
arr1=np.array([1,2,3,4,5,6])

In [229]:
for index,i in np.ndenumerate(arr1):
    print(index,i)
    

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6


## Enumerate on following 2D array's elements

In [230]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)


(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


## Enumerate on following 3D array's elements

In [231]:
arr3=np.array([[[1,2],[3,4],[5,6],[7,8]]])

In [232]:
for index,i in np.ndenumerate(arr3):
    print(index,i)
    

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(0, 2, 0) 5
(0, 2, 1) 6
(0, 3, 0) 7
(0, 3, 1) 8


# Joining NumPy Arrays

* ## 	Joining means putting contents of two or more arrays in a single array. You're joining them along an existing dimension (length of the table
* ##  We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0..


In [233]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [234]:
arr=np.concatenate((arr1,arr2))

In [235]:
arr

array([1, 2, 3, 4, 5, 6])

In [236]:
a=np.array([[1,2,3],[5,6,7]])
b=np.array([[11,12,13],[15,16,17]])

In [237]:
arr=np.concatenate((a,b))

In [238]:
arr

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [11, 12, 13],
       [15, 16, 17]])

In [239]:
arr1=np.concatenate((a,b),axis=1)

In [240]:
arr1

array([[ 1,  2,  3, 11, 12, 13],
       [ 5,  6,  7, 15, 16, 17]])

## Join two 2-D arrays along rows (axis=0)

In [241]:
arr1 = np.array([[2, 5,9], [4,1,3]])
arr2 = np.array([[5,8,3], [4,6, 1]])

In [242]:
arr=np.concatenate((arr1, arr2))
arr

array([[2, 5, 9],
       [4, 1, 3],
       [5, 8, 3],
       [4, 6, 1]])

## Join two 2-D arrays along columns (axis=1)

In [243]:
arr1 = np.array([[0,1, 3], [5,7, 9]])
arr2 = np.array([[0,2, 4], [6,8, 10]])

In [244]:
arr = np.concatenate((arr1, arr2),axis=1)
print(arr)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [245]:
three=np.arange(0,20)

In [246]:
three1=three.reshape(2,2,5)

In [247]:
three1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [248]:
threee=np.arange(10,30)

In [249]:
three2=threee.reshape(2,2,5)

In [250]:
three2

array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

## Join two 3-D arrays along rows (axis=0)

In [251]:
con=np.concatenate((three1,three2))

In [252]:
con

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

## Join two 3-D arrays along columns (axis=1)

In [253]:
con1=np.concatenate((three1,three2),axis=1)

In [254]:
con1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

# Joining Arrays Using Stack Functions

* ## Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
  
* ## Unlike the concatenate() function, the stack() function joins 1D arrays to be one 2D array and joins 2D arrays to be one 3D array.
  
* ## We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.
  
* ## We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.



# CHOOSING BETWEEN STACK AND CONCATENATION:

## The choice depends on your desired outcome:

* ## If you want to combine arrays with a new level of organization, use stack.
  
* ## If you simply want to join arrays along an existing dimension, use concatenate. 

In [255]:
arr1=np.array([1,2,3,4])
arr2=np.array([6,7,8,9])

In [256]:
# Row wise stack
stack=np.stack((arr1,arr2))
stack

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [257]:
# Column wise stack
stackc=np.stack((arr1,arr2),axis=1)
stackc

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

# Stacking Along Rows (hstack)

* ## NumPy provides a helper function: hstack() to stack along rows.
  
* ## Stacks arrays along the horizontal axis (column-wise)
  
* ## 1-D Arrays: The output is a 1-D array formed by concatenating the input arrays.
  
* ## 2-D Arrays: The output is a 2-D array where the input arrays are concatenated along the columns.
  
* ## Higher-Dimensional Arrays: The output has the same number of dimensions as the input arrays, but the second axis is increased to accommodate all input arrays.

	If Axis is 0, then it will join by first dimension
	If Axis is 1, the it will join by second dimension


In [258]:
hstack=np.hstack((arr1,arr2))

In [259]:
hstack

array([1, 2, 3, 4, 6, 7, 8, 9])

In [260]:
s1=np.array([[1,2,3],[5,6,7]])

In [261]:
s2=np.array([[11,12,13],[14,15,16]])

In [262]:
s=np.hstack((s1,s2))

In [263]:
s

array([[ 1,  2,  3, 11, 12, 13],
       [ 5,  6,  7, 14, 15, 16]])

In [264]:
t=np.arange(0,36)
t

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [265]:
threeft=t.reshape(3,4,3)
threeft

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [266]:
threeft.shape

(3, 4, 3)

In [267]:
threeft[1]

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [268]:
threeft[1,::]

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [269]:
threeft[1,::2]

array([[12, 13, 14],
       [18, 19, 20]])

In [270]:
threeft[1,:,::2]

array([[12, 14],
       [15, 17],
       [18, 20],
       [21, 23]])

In [271]:
threeft[1,:,1::2]

array([[13],
       [16],
       [19],
       [22]])

In [272]:
two=np.array([0,1,2,3,4,5,6,7,8,9,10],ndmin=2)

In [273]:
two

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [274]:
six=np.array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]],ndmin=6)

In [275]:
six

array([[[[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]]]]])

In [276]:
for i in np.nditer(six):
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [277]:
for index,i in np.ndenumerate(six):
    print(index,i)

(0, 0, 0, 0, 0, 0) 0
(0, 0, 0, 0, 0, 1) 1
(0, 0, 0, 0, 0, 2) 2
(0, 0, 0, 0, 0, 3) 3
(0, 0, 0, 0, 0, 4) 4
(0, 0, 0, 0, 0, 5) 5
(0, 0, 0, 0, 0, 6) 6
(0, 0, 0, 0, 0, 7) 7
(0, 0, 0, 0, 0, 8) 8
(0, 0, 0, 0, 0, 9) 9
(0, 0, 0, 0, 0, 10) 10


In [278]:
max=np.max(six)
min=np.min(six)
std=np.std(six)
var=np.var(six)
mean=np.mean(six)
sum=np.sum(six)

In [279]:
max

10

In [280]:
min

0

In [281]:
std

3.1622776601683795

In [282]:
var

10.0

In [283]:
mean

5.0

In [284]:
sum

55

In [285]:
two=np.array([[1,2,3,4],[5,6,7,8]])

In [286]:
tt=np.array([[1,5,6,7],[15,16,17,18]])

In [287]:
two

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [288]:
tt

array([[ 1,  5,  6,  7],
       [15, 16, 17, 18]])

In [289]:
arr=np.concatenate((two,tt),axis=0)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 1,  5,  6,  7],
       [15, 16, 17, 18]])

In [290]:
arr=np.concatenate((two,tt),axis=1)
arr

array([[ 1,  2,  3,  4,  1,  5,  6,  7],
       [ 5,  6,  7,  8, 15, 16, 17, 18]])

In [291]:
arr1=np.stack((two,tt),axis=0)
arr1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 1,  5,  6,  7],
        [15, 16, 17, 18]]])

In [292]:
arr1=np.stack((two,tt),axis=1)
arr1

array([[[ 1,  2,  3,  4],
        [ 1,  5,  6,  7]],

       [[ 5,  6,  7,  8],
        [15, 16, 17, 18]]])

In [293]:
arr3=np.hstack((two,tt))
arr3

array([[ 1,  2,  3,  4,  1,  5,  6,  7],
       [ 5,  6,  7,  8, 15, 16, 17, 18]])

# V Stack

In [294]:
arr3=np.vstack((two,tt))
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 1,  5,  6,  7],
       [15, 16, 17, 18]])

# Splitting NumPy Arrays
•	Splitting is reverse operation of Joining.

•	Joining merges multiple arrays into one and Splitting breaks one array into multiple.

•	We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

•	If the array has less elements than required, it will adjust from the end accordingly.


# Array_Split

In [295]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [296]:
new=np.array_split(arr,2)

In [297]:
new

[array([1, 2, 3]), array([4, 5, 6])]

In [298]:
new1=np.array_split(arr,3)
new1

[array([1, 2]), array([3, 4]), array([5, 6])]

In [299]:
new2=np.array_split(arr,4)
new2

[array([1, 2]), array([3, 4]), array([5]), array([6])]

# Split

In [300]:
arr=np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [301]:
a=np.split(arr,2)
a

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [302]:
b=np.split(arr,4)
b

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

## We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

In [303]:
tf=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [304]:
tf

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [305]:
#axis=0,row wise array split
two=np.array_split(tf,2)
two

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]])]

In [306]:
two=np.array_split(tf,2,axis=1)
two

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [307]:
split=np.split(tt,2,axis=1)
split

[array([[ 1,  5],
        [15, 16]]),
 array([[ 6,  7],
        [17, 18]])]

# Searching Arrays
•	You can search an array for a certain value, and return the indexes that get a match.

•	To search an array, use the where() method.

•	For replacing a value in a array using where()

•	np.where(condition, x, y)

•	condition: An array-like structure that contains boolean values (True or False).

•	x: The values to place in the output array where the condition is True
.
•	y: The values to place in the output array where the condition is False.


In [308]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 12])

In [309]:
x=np.where(arr==9)
x

(array([8], dtype=int64),)

In [310]:
x=np.where(arr==12)
x

(array([11, 16], dtype=int64),)

In [311]:
x=np.where(arr%2!=0)
x


(array([ 0,  2,  4,  6,  8, 10, 12, 14], dtype=int64),)

# replace elements in a list where values lessthan 5 with zero?

In [312]:
arr=np.array([1,2,3,4,5,10,11,12,13,14])
arr

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [313]:

x=np.where(arr<5,0,arr)
x

array([ 0,  0,  0,  0,  5, 10, 11, 12, 13, 14])

In [314]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [315]:
x=np.where(a==5)
x

(array([1], dtype=int64), array([1], dtype=int64))

In [316]:
y=np.where(a==12)
y


(array([3], dtype=int64), array([2], dtype=int64))

In [317]:
z=np.where(a%3==0,a+1,a)
z

array([[ 1,  2,  4],
       [ 4,  5,  7],
       [ 7,  8, 10],
       [10, 11, 13]])

In [318]:
arr=np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [319]:
x=arr.reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [320]:
z=np.where(x<3,x*-1,x)
z

array([[ 0, -1, -2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Sorting Arrays

•	Sorting means putting elements in an ordered sequence.
    
•	Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

•	The NumPy ndarray object has a function called sort(), that will sort a specified array.


In [321]:
arr=np.array([1,4,3,76,93,102,11,142])

In [322]:
x=np.sort(arr)
x

array([  1,   3,   4,  11,  76,  93, 102, 142])

In [323]:
x=np.sort(arr)[::-1]
x

array([142, 102,  93,  76,  11,   4,   3,   1])

In [324]:
arr2=arr.reshape(2,4)
arr2

array([[  1,   4,   3,  76],
       [ 93, 102,  11, 142]])

In [325]:
z=np.sort(arr2)
z

array([[  1,   3,   4,  76],
       [ 11,  93, 102, 142]])

In [326]:
y=np.sort(arr2)[::-1]

In [327]:
y

array([[ 11,  93, 102, 142],
       [  1,   3,   4,  76]])

In [328]:
q=np.sort(arr2)[::-1,::-1]
q

array([[142, 102,  93,  11],
       [ 76,   4,   3,   1]])

# Search Sorted (Optional)

•	There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

•	The searchsorted() method is assumed to be used on sorted arrays.

•	The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.


In [329]:
arr=np.array([4,5,6,7,8,9])
arr

array([4, 5, 6, 7, 8, 9])

In [330]:
ss=np.searchsorted(arr,7)
ss

3

## Search From the Right Side

•	By default the left most index is returned, but we can give side='right' to return the right most index instead.


In [331]:
arr=np.array([4,5,6,7,8,9])
arr

array([4, 5, 6, 7, 8, 9])

In [332]:
np.sort(arr)

array([4, 5, 6, 7, 8, 9])

In [333]:
ss=np.searchsorted(arr,7,side="right")
ss

4

In [334]:
ss=np.searchsorted(arr,7,side="left")
ss

3

# Filtering Arrays

•	Getting some elements out of an existing array and creating a new array out of them is called filtering.

•	In NumPy, you filter an array using a boolean index list.

•	A boolean index list is a list of booleans corresponding to indexes in the array.

•	If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.


In [335]:
a=np.array([41,42,43,44])
a

array([41, 42, 43, 44])

In [336]:
x=[True,False,True,False]


In [337]:
newarr=a[x]

In [338]:
newarr

array([41, 43])

In [339]:
b=np.array([41,42,43,44,45,46])
b

array([41, 42, 43, 44, 45, 46])

In [340]:
filter_array=[]

In [341]:
for i in b:
    if i>44:
        filter_array.append(True)
    else:
        filter_array.append(False)
        
newarr=b[filter_array]        

In [342]:
filter_array

[False, False, False, False, True, True]

In [343]:
newarr

array([45, 46])

# Creating Filter Directly From Array

•	We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.
    
•	Create a filter array that will return only values higher than 42:

•	import numpy as np


In [344]:
arr = np.array([41, 42, 43, 44])

In [345]:
filter_arr=arr>42

In [346]:
filter_arr

array([False, False,  True,  True])

In [347]:
newarr=arr[filter_arr]

In [348]:
newarr

array([43, 44])

# Random Numbers

* ### Random numbers are numbers that are generated in such a way that each number has an equal probability of being chosen within a specified range.

* ### Random Numbers are used in a wide range of applications, from scientific simulations to cryptography (including key generation, encryption, digital signatures, and secure communication protocols) and gaming (
  ### * Random Events (The locations and times at which enemies appear can be controlled by random numbers to keep gameplay unpredictable and engaging)
  ### * Randomized Outcomes (Shuffling a deck of cards in digital card games relies on random numbers to ensure fair play and unpredictability).)
* ### However, not all random numbers are created equal. They can be broadly categorized into two types:
 	### * pseudo-random numbers 
 	### * True random numbers.



# True Random Numbers
#### True Random Numbers are generated from physical processes that are inherently unpredictable, like radioactive decay or atmospheric noise.
#### •	Unpredictable: Their next value can't be guessed.

#### •	Examples: Flipping a coin, rolling a dice, measuring radioactive decay.


# Pseudo-Random Numbers

#### Pseudo-Random Numbers are generated using algorithms and a starting value called a seed. They appear random, but are actually predictable if you know the seed.
#### •	Deterministic: If you start with the same seed, you get the same sequence of numbers.
#### •	Examples: Random numbers generated by computer algorithms like the Linear Congruential Generator (LCG).



###  True Random Numbers: Best for cryptographic applications because they are truly unpredictable.

###  Pseudo-Random Numbers: Suitable for non-cryptographic applications where high speed and reproducibility are important..

# Random Number Generation in NumPy

### •	Python defines a set of functions that are used to generate or manipulate random numbers through the random module. 
### •	Functions in the random module rely on a pseudo-random number generator function random(), which generates a random float number between 0.0 and 1.0.
### •	This particular type of functions is used in a lot of games, lotteries, or any application requiring a random number generation.


## Basic Random Number Generation

In [362]:
# 1.Single Random Float

random_float = np.random.rand()
random_float # Generates a random float between 0 and 1


0.864093407726774

In [359]:
# 2.Array of Random Integers:

random_integers = np.random.randint(10, 60, size=10)
random_integers
         # Generates an array of 10 random integers between 10 and 60

array([23, 18, 13, 59, 51, 43, 59, 29, 48, 39])

In [367]:
random_integers = np.random.randint(10, 60)
random_integers

11

# Random Arrays

# 2D Array of Random Floats:

In [368]:
random_2d_array = np.random.rand(3,3)
print(random_2d_array)  
# Generates a 3x3 array of random floats between 0 and 1


[[0.56991204 0.94771142 0.49286874]
 [0.23905897 0.43137553 0.39273553]
 [0.4964024  0.78811272 0.12895477]]


In [369]:
random_float = np.random.rand(2,5)
random_float

array([[0.43198762, 0.72808377, 0.19282012, 0.88659212, 0.71387661],
       [0.41949739, 0.48466426, 0.468095  , 0.6166853 , 0.23904374]])

# Using random.uniform

In [380]:
# Generate a single random float between 5 and 10 

random_float_uniform = np.random.uniform(5, 10)
random_float_uniform

5.800636403428497

In [376]:
float=np.random.uniform(1,10)
float

9.096925578931096

In [377]:
# Generate an array of 5 random floats between 5 and 10 

random_floats_uniform = np.random.uniform(5, 10, 5) 
random_floats_uniform

array([6.45081126, 5.73168839, 6.09835954, 7.45922638, 6.84696044])

In [378]:
random_float=np.random.uniform(20,50,4)
random_float

array([34.34542689, 22.94558576, 22.02170401, 38.46794234])

# 1D Array from Normal Distribution:

In [384]:
random_normal = np.random.randn(10)
random_normal  
# Generates a 1D array of 10 random numbers from a standard normal distribution


array([ 1.63740273, -0.15326932,  0.34700227,  0.02556823,  0.3370685 ,
        0.14395074, -0.26988823, -0.05595809,  2.4889588 , -1.13099525])

# Random Choice

## 1.Without Replacement:

In [388]:
# Generates a random sample of 3 elements without replacement
random_sample =np.random.choice([1,2,3,4,5,6], size=3, replace=False)
random_sample

array([5, 3, 2])

In [389]:
random_sample =np.random.choice([1,2,3,4,5,6], size=3, replace=False)
random_sample

array([3, 1, 4])

## 2.With Replacement:

In [391]:
# Generates a random sample of 3 elements with replacement
random_sample_with_replacement = np.random.choice([10, 20, 30, 40, 50], size=3, replace=True)
random_sample_with_replacement

array([10, 20, 10])

# Setting a Seed
* ### Setting a seed ensures reproducibility of random number sequences:


In [397]:
# The same array will be generated every time this code is run
np.random.seed(42)
array = np.random.rand(5)
array 

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [398]:
np.random.seed(34)
array = np.random.rand(4)
array 

array([0.03856168, 0.78010046, 0.09270376, 0.63289269])

# Shuffling

## 1.Shuffle Array Elements:

In [399]:
array= np.array([1, 2, 3, 4, 5])
np.random.shuffle(array)
print(array) 
          # Shuffles the elements of the array in-place


[1 2 5 3 4]


In [402]:
array= np.array([100,101,102,103,104,105])
np.random.shuffle(array)
print(array) 


[100 102 101 103 104 105]


# 2.Shuffle Rows of a 2D Array:

In [403]:
# Shuffles the rows of the 2D array
array_2d = np.array([[1, 2], [3, 4], [5, 6]])
np.random.shuffle(array_2d)
print(array_2d)  

[[3 4]
 [5 6]
 [1 2]]


# Statistical Distributions

## 1.Uniform Distribution:
### Uniform Distribution is a type of probability distribution where all outcomes are equally likely. Each value within a specified range has an equal probability of occurring. This distribution is often used when there is no reason to prefer one outcome over another.


In [408]:
# Generate 10 random floats between -1 and 1
uniform_random_numbers = np.random.uniform(-1, 1, size=10)
uniform_random_numbers

array([ 0.98910838,  0.83136379,  0.16540432, -0.94227985,  0.39016405,
       -0.0160459 ,  0.22250362, -0.18025103, -0.28315918,  0.90689567])

# 2.Poisson Distribution:

### Poisson Distribution is a probability distribution that models the number of events occurring within a fixed interval of time or space, given the events happen with a known constant rate and are independent of the time since the last event. It is often used to model rare events.


In [412]:
# Generate 10 random numbers from a Poisson distribution with lambda = 3
poisson_random_numbers = np.random.poisson(lam=5, size=10)
poisson_random_numbers

array([ 7,  4,  2,  6,  4,  6,  5,  6, 10,  7])