In [151]:
import numpy as np

1.	Explain the difference between deep copy and shallow copy in NumPy arrays.

### deep copy
* deep copy is a copy where the any changes in the original does not change in copy.
### shallow copy
* shallow copy is a copy where the changes in original change in the copy.

2.	Explain the difference between array and list?


### array
* array contain same data type
* less memory usage
* stored in contigenously location
* item wise computetion is possible
### list
* a list contain different types of data types.
* list have huge memory usage

3.	Given an array a = np.array([10, 20, 30]), how do you square every element in the array?

In [152]:
arr=np.array([10, 20, 30])

In [153]:
square=np.square(arr)
square

array([100, 400, 900])

4.	How do you create an array of zeros with shape (3, 4)?

In [154]:
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

5.	Given the 1D array a = np.array([1, 2, 3, 4, 5]), how do you calculate the cumulative sum of the elements?

In [155]:
 a = np.array([1, 2, 3, 4, 5])

In [156]:
sum=np.sum(a)
sum

15

6.	How do you reverse the elements in a NumPy array a = np.array([1, 2, 3, 4, 5])?

In [157]:
 a = np.array([1, 2, 3, 4, 5])
a[::-1]

array([5, 4, 3, 2, 1])

7.	How do you find the indices of elements that are greater than 4 in the array a = np.array([1, 2, 3, 4, 5, 6, 7])?

In [158]:
 a = np.array([1, 2, 3, 4, 5, 6, 7])

In [159]:
for idx,i in np.ndenumerate(a):
    if i>4:
       print(idx,i)

(4,) 5
(5,) 6
(6,) 7


8.	How do you create a 2D array with random floating-point numbers between 0 and 1 of shape (3, 3)?

In [160]:
arr=np.random.rand(3,3)

In [161]:
arr

array([[0.65989286, 0.52160858, 0.33508355],
       [0.72385318, 0.63871655, 0.64396557],
       [0.38642008, 0.08261853, 0.42470223]])

9.	Extract the elements at indices [0, 2, 4] from the array a = np.array([10, 20, 30, 40, 50]).

In [162]:
 a = np.array([10, 20, 30, 40, 50])

In [163]:
a[0::2]

array([10, 30, 50])

In [164]:
a[0]

10

In [165]:
a[2]

30

In [166]:
a[4]

50

10.	Given the array a = np.array([10, 20, 30, 40]), how do you normalize the array so that its values are between 0 and 1?

In [167]:
 a = np.array([10, 20, 30, 40])

In [168]:
normalize=(a-np.min(a))/(np.max(a)-np.min(a))
normalize

array([0.        , 0.33333333, 0.66666667, 1.        ])

11.	How do you concatenate two arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) along the first axis?

In [169]:
 a = np.array([1, 2, 3])
 b = np.array([4, 5, 6])
c=np.concatenate((a,b),axis=0)
c

array([1, 2, 3, 4, 5, 6])

12.	How do you find the dot product of two arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6])?

In [170]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=np.dot(a,b)
c

32

13.	How do you create an identity matrix of size 4x4?

In [171]:
a=np.eye(4,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

14.	How do you generate an array with random integers between 1 and 100, of shape (4, 4)?

In [172]:
a=np.random.randint(1,100,size=(4,4))
a

array([[74, 29, 58, 87],
       [74, 71, 71, 55],
       [88, 80,  7, 83],
       [67, 64, 36, 52]])

15.	How do you split a NumPy array a = np.array([1, 2, 3, 4, 5, 6]) into three sub-arrays?

In [173]:
 a = np.array([1, 2, 3, 4, 5, 6])
b=np.split(a,3)
b

[array([1, 2]), array([3, 4]), array([5, 6])]

16.	Given the 2D array a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), how do you compute the sum of all elements along the second axis?

In [174]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b=np.sum(a,axis=1)
b

array([ 6, 15, 24])

17.	How do you compute the element-wise maximum of two arrays a = np.array([1, 2, 3]) and b = np.array([3, 2, 1])?

In [175]:
a = np.array([1, 2, 3]) 
b = np.array([3, 2, 1])
c=np.maximum(a,b)
c

array([3, 2, 3])

18.	How do you find the unique elements in the array a = np.array([1, 2, 2, 3, 3, 4, 5])?

In [176]:
a = np.array([1, 2, 2, 3, 3, 4, 5])
b=np.unique(a)  
b

array([1, 2, 3, 4, 5])

19.	How do you use np.arange to create an array of values between 1 and 50 with a step of 3, and then filter the elements that are divisible by 5?

In [187]:
a=np.arange(1,50,3)
list=a%5==0
list=a[list]
print(list)

[10 25 40]


20.	Given the array a = np.array([1, 2, 3, 4, 5]) and b = np.array([6, 7, 8, 9, 10]), use np.where to replace elements in a that are less than 3 with -3, then  horizontally stack a and b.

In [196]:
a = np.array([1, 2, 3, 4, 5]) 
b = np.array([6, 7, 8, 9, 10])
a=np.where(a<3,-3,a)
d=np.hstack((a,b))
d

array([-3, -3,  3,  4,  5,  6,  7,  8,  9, 10])

21.	How do you generate a 3D array of shape (4, 3, 2) where each 2D slice (3x2) is filled with random values between 0 and 1, and then normalize the entire 3D array to values between 0 and 1 (with respect to the min and max of the array)?

In [211]:
np.random.seed(42)
a=np.random.rand(4,3,2)
a

array([[[0.37454012, 0.95071431],
        [0.73199394, 0.59865848],
        [0.15601864, 0.15599452]],

       [[0.05808361, 0.86617615],
        [0.60111501, 0.70807258],
        [0.02058449, 0.96990985]],

       [[0.83244264, 0.21233911],
        [0.18182497, 0.18340451],
        [0.30424224, 0.52475643]],

       [[0.43194502, 0.29122914],
        [0.61185289, 0.13949386],
        [0.29214465, 0.36636184]]])

In [212]:
normalize=(a-np.min(a))/(np.max(a)-np.min(a))
normalize

array([[[0.37284965, 0.9797798 ],
        [0.74938422, 0.60893137],
        [0.14266357, 0.14263816]],

       [[0.03950081, 0.89072903],
        [0.61151903, 0.72418595],
        [0.        , 1.        ]],

       [[0.85519484, 0.20199041],
        [0.16984743, 0.17151129],
        [0.2987993 , 0.53108445]],

       [[0.4333188 , 0.28509156],
        [0.62283009, 0.12525671],
        [0.28605594, 0.36423482]]])

22.	Given a 2D array of shape (5, 5) filled with random integers between 1 and 100, replace all odd numbers with -1 and all even numbers with 1.

In [228]:
np.random.seed(42)
a=np.random.randint(1,100,size=(5,5))
a

array([[52, 93, 15, 72, 61],
       [21, 83, 87, 75, 75],
       [88, 24,  3, 22, 53],
       [ 2, 88, 30, 38,  2],
       [64, 60, 21, 33, 76]])

In [231]:
a=np.where(a%2!=0,-1,1)
a

array([[ 1, -1, -1,  1, -1],
       [-1, -1, -1, -1, -1],
       [ 1,  1, -1,  1, -1],
       [ 1,  1,  1,  1,  1],
       [ 1,  1, -1, -1,  1]])

23.	Given a large 1D array of 10 million random floating-point numbers between 0 and 1, find the 10th and 90th percentile of the values.

In [235]:
a=np.random.rand(10000000)
percentile= np.percentile(a,10)   
percentile

0.09991866435149882

In [236]:
percentile= np.percentile(a,90)   
percentile

0.8999591777649296

24.	Given a 5x5 matrix arr, use np.where to:
•	Replace all elements greater than 10 with the value 100.
•	Replace all elements less than or equal to 10 with the value -100


In [248]:
a=np.arange(0,25)
a=a.reshape(5,5)

In [249]:
a=np.where(a>10,100,-100)

In [250]:
a

array([[-100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100],
       [-100,  100,  100,  100,  100],
       [ 100,  100,  100,  100,  100],
       [ 100,  100,  100,  100,  100]])

25.	Given a 2D array arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]), perform the following operations:
•	Horizontally split the array into two equal parts.
•	Vertically split the array into three equal parts.
•	Stack the split parts vertically and horizontally.


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [264]:
h=np.array_split(arr,2,axis=1)
h

[array([[0.65989286, 0.52160858],
        [0.72385318, 0.63871655],
        [0.38642008, 0.08261853]]),
 array([[0.33508355],
        [0.64396557],
        [0.42470223]])]

In [254]:
v=np.array_split(arr,3)
v

[array([[0.65989286, 0.52160858, 0.33508355]]),
 array([[0.72385318, 0.63871655, 0.64396557]]),
 array([[0.38642008, 0.08261853, 0.42470223]])]